version: "3.9"

services:
  backend:
    image: fit-forge-muscu-backend
    build:
      context: ./backend
    container_name: muscu-pwa-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - /opt/fitforge-data/dev.db:/app/dev.db
    restart: always

  frontend:
    image: fit-forge-muscu-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: https://api.fitforge-muscu.fr
    container_name: muscu-pwa-frontend
    ports:
      - "5173:80"
    restart: always
